# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937b8aab652b94c2049e77899efeef39a83115d7f29aa81a27a5ce950348c1cfebbf9e3f7d6c4b9ad25809d92340df1e0cf5dc16082ae1347cdf6ddf8acc8243

test:
  secret_key_base: 14bc1915f64a49a3e289f4b9cc9bcf9856c288e17f62cb4bff04a5b1df4a58bac1d4a3b0dde9524a31978517b9e376604b8113ac2f24a6d8c4420f6b348c0651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
